version: '3'

services:
  angular:
    container_name: angular
    networks:
      - transcendence
    build:
      context: ./src/angular
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - angular:/var/www/angular
    depends_on:
      - nestjs
    restart: on-failure

  nestjs:
    container_name: nestjs
    networks:
      - transcendence
    build:
      context: ./src/nestjs
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
      - "3000:3000"
    volumes:
      - nestjs:/var/www/nestjs
    restart: on-failure


volumes:
  angular:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './volume/angular'
  
  nestjs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './volume/nestjs'

networks:
  transcendence:
    driver: bridge