version: '3'

services:
  angular:
    container_name: angular
    networks:
      - transcendence
    build:
      context: ./angular
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
#    volumes:
#      - angular:/var/www/angular
    restart: unless-stopped

#volumes:
#  angular:
#    driver: local
#    driver_opts:
#      type: 'none'
#      o: 'bind'
#      device: './volume/angular'

networks:
  transcendence:
    driver: bridge